# Just uncomment any of config options to get it.

service: randomFunc-noExpress
provider:
  name: aws
  runtime: nodejs12.x
  profile: sls
  stage: dev
  region: us-east-1
  memorySize: 128 # optional, in MB, default is 1024
  timeout: 1 # optional, in seconds, default is 6
  include:
    - node_modules/**
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  random:
    handler: handler.server
    events:
      - http:
          path: /
          method: GET
          cors:
            origin: "*"

resources:
  Resources:
    ApiPathMapping:
      Type: AWS::ApiGateway::BasePathMapping
      DependsOn: ApiGatewayRestApi
      Properties:
        BasePath: random
        Stage: ${self:provider.stage}
        RestApiId:
          Ref: ApiGatewayRestApi
        DomainName: "dev-api.gotdadjoke.com"
